from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.openapi_server import util
from server.openapi_server.models.base_model import Model
from server.openapi_server.models.meeting import Meeting


class Teacher(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, phone=None, email=None, about_section=None, available=None, rating=None, subjects_to_teach=None, hourly_rate=None, meetings=None):  # noqa: E501
        """Teacher - a model defined in OpenAPI

        :param id: The id of this Teacher.  # noqa: E501
        :type id: int
        :param name: The name of this Teacher.  # noqa: E501
        :type name: str
        :param phone: The phone of this Teacher.  # noqa: E501
        :type phone: str
        :param email: The email of this Teacher.  # noqa: E501
        :type email: str
        :param about_section: The about_section of this Teacher.  # noqa: E501
        :type about_section: str
        :param available: The available of this Teacher.  # noqa: E501
        :type available: List[datetime]
        :param rating: The rating of this Teacher.  # noqa: E501
        :type rating: float
        :param subjects_to_teach: The subjects_to_teach of this Teacher.  # noqa: E501
        :type subjects_to_teach: List[str]
        :param hourly_rate: The hourly_rate of this Teacher.  # noqa: E501
        :type hourly_rate: float
        :param meetings: The meetings of this Teacher.  # noqa: E501
        :type meetings: List[Meeting]
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'phone': str,
            'email': str,
            'about_section': str,
            'available': List[datetime],
            'rating': float,
            'subjects_to_teach': List[str],
            'hourly_rate': float,
            'meetings': List[Meeting]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'phone': 'phone',
            'email': 'email',
            'about_section': 'about_section',
            'available': 'available',
            'rating': 'rating',
            'subjects_to_teach': 'subjects_to_teach',
            'hourly_rate': 'hourly_rate',
            'meetings': 'meetings'
        }

        self._id = id
        self._name = name
        self._phone = phone
        self._email = email
        self._about_section = about_section
        self._available = available
        self._rating = rating
        self._subjects_to_teach = subjects_to_teach
        self._hourly_rate = hourly_rate
        self._meetings = meetings

    @classmethod
    def from_dict(cls, dikt) -> 'Teacher':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Teacher of this Teacher.  # noqa: E501
        :rtype: Teacher
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Teacher.


        :return: The id of this Teacher.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Teacher.


        :param id: The id of this Teacher.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Teacher.


        :return: The name of this Teacher.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Teacher.


        :param name: The name of this Teacher.
        :type name: str
        """

        self._name = name

    @property
    def phone(self) -> str:
        """Gets the phone of this Teacher.


        :return: The phone of this Teacher.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this Teacher.


        :param phone: The phone of this Teacher.
        :type phone: str
        """

        self._phone = phone

    @property
    def email(self) -> str:
        """Gets the email of this Teacher.


        :return: The email of this Teacher.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Teacher.


        :param email: The email of this Teacher.
        :type email: str
        """

        self._email = email

    @property
    def about_section(self) -> str:
        """Gets the about_section of this Teacher.


        :return: The about_section of this Teacher.
        :rtype: str
        """
        return self._about_section

    @about_section.setter
    def about_section(self, about_section: str):
        """Sets the about_section of this Teacher.


        :param about_section: The about_section of this Teacher.
        :type about_section: str
        """

        self._about_section = about_section

    @property
    def available(self) -> List[datetime]:
        """Gets the available of this Teacher.


        :return: The available of this Teacher.
        :rtype: List[datetime]
        """
        return self._available

    @available.setter
    def available(self, available: List[datetime]):
        """Sets the available of this Teacher.


        :param available: The available of this Teacher.
        :type available: List[datetime]
        """

        self._available = available

    @property
    def rating(self) -> float:
        """Gets the rating of this Teacher.

        Average rating for the person, on a scale of 0 to 5.  # noqa: E501

        :return: The rating of this Teacher.
        :rtype: float
        """
        return self._rating

    @rating.setter
    def rating(self, rating: float):
        """Sets the rating of this Teacher.

        Average rating for the person, on a scale of 0 to 5.  # noqa: E501

        :param rating: The rating of this Teacher.
        :type rating: float
        """

        self._rating = rating

    @property
    def subjects_to_teach(self) -> List[str]:
        """Gets the subjects_to_teach of this Teacher.


        :return: The subjects_to_teach of this Teacher.
        :rtype: List[str]
        """
        return self._subjects_to_teach

    @subjects_to_teach.setter
    def subjects_to_teach(self, subjects_to_teach: List[str]):
        """Sets the subjects_to_teach of this Teacher.


        :param subjects_to_teach: The subjects_to_teach of this Teacher.
        :type subjects_to_teach: List[str]
        """

        self._subjects_to_teach = subjects_to_teach

    @property
    def hourly_rate(self) -> float:
        """Gets the hourly_rate of this Teacher.


        :return: The hourly_rate of this Teacher.
        :rtype: float
        """
        return self._hourly_rate

    @hourly_rate.setter
    def hourly_rate(self, hourly_rate: float):
        """Sets the hourly_rate of this Teacher.


        :param hourly_rate: The hourly_rate of this Teacher.
        :type hourly_rate: float
        """

        self._hourly_rate = hourly_rate

    @property
    def meetings(self) -> List[Meeting]:
        """Gets the meetings of this Teacher.


        :return: The meetings of this Teacher.
        :rtype: List[Meeting]
        """
        return self._meetings

    @meetings.setter
    def meetings(self, meetings: List[Meeting]):
        """Sets the meetings of this Teacher.


        :param meetings: The meetings of this Teacher.
        :type meetings: List[Meeting]
        """

        self._meetings = meetings
